permissions:
  contents: write

name: Update README

on:
  schedule:
    - cron: '0 0 * * *'    
  workflow_dispatch: {}    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build & run generator
        working-directory: ReadmeGenerator
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet run --configuration Release
          
      - name: Commit & push changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet || git commit -m "chore: update README"
          git push
